#baseURL = "/"
baseURL = "https://www.perbabymobile.de/perbabymobile.de/"
languageCode = "de-de"
title = "PerBabyMobile"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "PerBabyMobile"

  [params.homepage_meta_tags]
    meta_description = "PerBabyMobile entstand im Sommer 2000 als erstes und einziges Spiel- und Bewegungszentrum für Babys und Kleinkinder in Frankfurt. Ein Spielraum, der speziell für Babys und Kleinkinder eingerichtet wurde."
    meta_og_title = "PerBabyMobile"
    meta_og_type = "website"
    meta_og_url = "https://lnnwvr.github.io/perbabymobile-test.github.io/"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "PerBabyMobile entstand im Sommer 2000 als erstes und einziges Spiel- und Bewegungszentrum für Babys und Kleinkinder in Frankfurt. Ein Spielraum, der speziell für Babys und Kleinkinder eingerichtet wurde."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Angebote"
	url = "/services/"
    weight = 2

[[menu.main]]
    name = "Musik"
    url = "/work/"
    weight = 3

[[menu.main]]
    name = "Über Uns"
    url = "/about/"
    weight = 1


[[menu.main]]
    name = "Kontakt"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
